In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
ds=pd.read_csv("D:\president_heights.csv")

In [3]:
ds

    order                    name  height(cm)
0       1       George Washington         189
1       2              John Adams         170
2       3        Thomas Jefferson         189
3       4           James Madison         163
4       5            James Monroe         183
5       6       John Quincy Adams         171
6       7          Andrew Jackson         185
7       8        Martin Van Buren         168
8       9  William Henry Harrison         173
9      10              John Tyler         183
10     11           James K. Polk         173
11     12          Zachary Taylor         173
12     13        Millard Fillmore         175
13     14         Franklin Pierce         178
14     15          James Buchanan         183
15     16         Abraham Lincoln         193
16     17          Andrew Johnson         178
17     18        Ulysses S. Grant         173
18     19     Rutherford B. Hayes         174
19     20       James A. Garfield         183
20     21       Chester A. Arthur         183
21     23       Benjamin Harrison         168
22     25        William McKinley         170
23     26      Theodore Roosevelt         178
24     27     William Howard Taft         182
25     28          Woodrow Wilson         180
26     29       Warren G. Harding         183
27     30         Calvin Coolidge         178
28     31          Herbert Hoover         182
29     32   Franklin D. Roosevelt         188
30     33         Harry S. Truman         175
31     34    Dwight D. Eisenhower         179
32     35         John F. Kennedy         183
33     36       Lyndon B. Johnson         193
34     37           Richard Nixon         182
35     38             Gerald Ford         183
36     39            Jimmy Carter         177
37     40           Ronald Reagan         185
38     41       George H. W. Bush         188
39     42            Bill Clinton         188
40     43          George W. Bush         182
41     44            Barack Obama         185

In [4]:
ds.rename(columns={'height(cm)':'new readings'})

    order                    name  new readings
0       1       George Washington           189
1       2              John Adams           170
2       3        Thomas Jefferson           189
3       4           James Madison           163
4       5            James Monroe           183
5       6       John Quincy Adams           171
6       7          Andrew Jackson           185
7       8        Martin Van Buren           168
8       9  William Henry Harrison           173
9      10              John Tyler           183
10     11           James K. Polk           173
11     12          Zachary Taylor           173
12     13        Millard Fillmore           175
13     14         Franklin Pierce           178
14     15          James Buchanan           183
15     16         Abraham Lincoln           193
16     17          Andrew Johnson           178
17     18        Ulysses S. Grant           173
18     19     Rutherford B. Hayes           174
19     20       James A. Garfield           183
20     21       Chester A. Arthur           183
21     23       Benjamin Harrison           168
22     25        William McKinley           170
23     26      Theodore Roosevelt           178
24     27     William Howard Taft           182
25     28          Woodrow Wilson           180
26     29       Warren G. Harding           183
27     30         Calvin Coolidge           178
28     31          Herbert Hoover           182
29     32   Franklin D. Roosevelt           188
30     33         Harry S. Truman           175
31     34    Dwight D. Eisenhower           179
32     35         John F. Kennedy           183
33     36       Lyndon B. Johnson           193
34     37           Richard Nixon           182
35     38             Gerald Ford           183
36     39            Jimmy Carter           177
37     40           Ronald Reagan           185
38     41       George H. W. Bush           188
39     42            Bill Clinton           188
40     43          George W. Bush           182
41     44            Barack Obama           185

In [5]:
ds

    order                    name  height(cm)
0       1       George Washington         189
1       2              John Adams         170
2       3        Thomas Jefferson         189
3       4           James Madison         163
4       5            James Monroe         183
5       6       John Quincy Adams         171
6       7          Andrew Jackson         185
7       8        Martin Van Buren         168
8       9  William Henry Harrison         173
9      10              John Tyler         183
10     11           James K. Polk         173
11     12          Zachary Taylor         173
12     13        Millard Fillmore         175
13     14         Franklin Pierce         178
14     15          James Buchanan         183
15     16         Abraham Lincoln         193
16     17          Andrew Johnson         178
17     18        Ulysses S. Grant         173
18     19     Rutherford B. Hayes         174
19     20       James A. Garfield         183
20     21       Chester A. Arthur         183
21     23       Benjamin Harrison         168
22     25        William McKinley         170
23     26      Theodore Roosevelt         178
24     27     William Howard Taft         182
25     28          Woodrow Wilson         180
26     29       Warren G. Harding         183
27     30         Calvin Coolidge         178
28     31          Herbert Hoover         182
29     32   Franklin D. Roosevelt         188
30     33         Harry S. Truman         175
31     34    Dwight D. Eisenhower         179
32     35         John F. Kennedy         183
33     36       Lyndon B. Johnson         193
34     37           Richard Nixon         182
35     38             Gerald Ford         183
36     39            Jimmy Carter         177
37     40           Ronald Reagan         185
38     41       George H. W. Bush         188
39     42            Bill Clinton         188
40     43          George W. Bush         182
41     44            Barack Obama         185

In [7]:
ds.rename(columns={'height(cm)':'new readings'},inplace=True)

In [8]:
ds

    order                    name  new readings
0       1       George Washington           189
1       2              John Adams           170
2       3        Thomas Jefferson           189
3       4           James Madison           163
4       5            James Monroe           183
5       6       John Quincy Adams           171
6       7          Andrew Jackson           185
7       8        Martin Van Buren           168
8       9  William Henry Harrison           173
9      10              John Tyler           183
10     11           James K. Polk           173
11     12          Zachary Taylor           173
12     13        Millard Fillmore           175
13     14         Franklin Pierce           178
14     15          James Buchanan           183
15     16         Abraham Lincoln           193
16     17          Andrew Johnson           178
17     18        Ulysses S. Grant           173
18     19     Rutherford B. Hayes           174
19     20       James A. Garfield           183
20     21       Chester A. Arthur           183
21     23       Benjamin Harrison           168
22     25        William McKinley           170
23     26      Theodore Roosevelt           178
24     27     William Howard Taft           182
25     28          Woodrow Wilson           180
26     29       Warren G. Harding           183
27     30         Calvin Coolidge           178
28     31          Herbert Hoover           182
29     32   Franklin D. Roosevelt           188
30     33         Harry S. Truman           175
31     34    Dwight D. Eisenhower           179
32     35         John F. Kennedy           183
33     36       Lyndon B. Johnson           193
34     37           Richard Nixon           182
35     38             Gerald Ford           183
36     39            Jimmy Carter           177
37     40           Ronald Reagan           185
38     41       George H. W. Bush           188
39     42            Bill Clinton           188
40     43          George W. Bush           182
41     44            Barack Obama           185

In [9]:
ds

    order                    name  new readings
0       1       George Washington           189
1       2              John Adams           170
2       3        Thomas Jefferson           189
3       4           James Madison           163
4       5            James Monroe           183
5       6       John Quincy Adams           171
6       7          Andrew Jackson           185
7       8        Martin Van Buren           168
8       9  William Henry Harrison           173
9      10              John Tyler           183
10     11           James K. Polk           173
11     12          Zachary Taylor           173
12     13        Millard Fillmore           175
13     14         Franklin Pierce           178
14     15          James Buchanan           183
15     16         Abraham Lincoln           193
16     17          Andrew Johnson           178
17     18        Ulysses S. Grant           173
18     19     Rutherford B. Hayes           174
19     20       James A. Garfield           183
20     21       Chester A. Arthur           183
21     23       Benjamin Harrison           168
22     25        William McKinley           170
23     26      Theodore Roosevelt           178
24     27     William Howard Taft           182
25     28          Woodrow Wilson           180
26     29       Warren G. Harding           183
27     30         Calvin Coolidge           178
28     31          Herbert Hoover           182
29     32   Franklin D. Roosevelt           188
30     33         Harry S. Truman           175
31     34    Dwight D. Eisenhower           179
32     35         John F. Kennedy           183
33     36       Lyndon B. Johnson           193
34     37           Richard Nixon           182
35     38             Gerald Ford           183
36     39            Jimmy Carter           177
37     40           Ronald Reagan           185
38     41       George H. W. Bush           188
39     42            Bill Clinton           188
40     43          George W. Bush           182
41     44            Barack Obama           185

In [10]:
ds.insert(3,"quality","Good")

In [11]:
ds

    order                    name  new readings quality
0       1       George Washington           189    Good
1       2              John Adams           170    Good
2       3        Thomas Jefferson           189    Good
3       4           James Madison           163    Good
4       5            James Monroe           183    Good
5       6       John Quincy Adams           171    Good
6       7          Andrew Jackson           185    Good
7       8        Martin Van Buren           168    Good
8       9  William Henry Harrison           173    Good
9      10              John Tyler           183    Good
10     11           James K. Polk           173    Good
11     12          Zachary Taylor           173    Good
12     13        Millard Fillmore           175    Good
13     14         Franklin Pierce           178    Good
14     15          James Buchanan           183    Good
15     16         Abraham Lincoln           193    Good
16     17          Andrew Johnson           178    Good
17     18        Ulysses S. Grant           173    Good
18     19     Rutherford B. Hayes           174    Good
19     20       James A. Garfield           183    Good
20     21       Chester A. Arthur           183    Good
21     23       Benjamin Harrison           168    Good
22     25        William McKinley           170    Good
23     26      Theodore Roosevelt           178    Good
24     27     William Howard Taft           182    Good
25     28          Woodrow Wilson           180    Good
26     29       Warren G. Harding           183    Good
27     30         Calvin Coolidge           178    Good
28     31          Herbert Hoover           182    Good
29     32   Franklin D. Roosevelt           188    Good
30     33         Harry S. Truman           175    Good
31     34    Dwight D. Eisenhower           179    Good
32     35         John F. Kennedy           183    Good
33     36       Lyndon B. Johnson           193    Good
34     37           Richard Nixon           182    Good
35     38             Gerald Ford           183    Good
36     39            Jimmy Carter           177    Good
37     40           Ronald Reagan           185    Good
38     41       George H. W. Bush           188    Good
39     42            Bill Clinton           188    Good
40     43          George W. Bush           182    Good
41     44            Barack Obama           185    Good

In [12]:
ds.drop(columns=['quality'])

    order                    name  new readings
0       1       George Washington           189
1       2              John Adams           170
2       3        Thomas Jefferson           189
3       4           James Madison           163
4       5            James Monroe           183
5       6       John Quincy Adams           171
6       7          Andrew Jackson           185
7       8        Martin Van Buren           168
8       9  William Henry Harrison           173
9      10              John Tyler           183
10     11           James K. Polk           173
11     12          Zachary Taylor           173
12     13        Millard Fillmore           175
13     14         Franklin Pierce           178
14     15          James Buchanan           183
15     16         Abraham Lincoln           193
16     17          Andrew Johnson           178
17     18        Ulysses S. Grant           173
18     19     Rutherford B. Hayes           174
19     20       James A. Garfield           183
20     21       Chester A. Arthur           183
21     23       Benjamin Harrison           168
22     25        William McKinley           170
23     26      Theodore Roosevelt           178
24     27     William Howard Taft           182
25     28          Woodrow Wilson           180
26     29       Warren G. Harding           183
27     30         Calvin Coolidge           178
28     31          Herbert Hoover           182
29     32   Franklin D. Roosevelt           188
30     33         Harry S. Truman           175
31     34    Dwight D. Eisenhower           179
32     35         John F. Kennedy           183
33     36       Lyndon B. Johnson           193
34     37           Richard Nixon           182
35     38             Gerald Ford           183
36     39            Jimmy Carter           177
37     40           Ronald Reagan           185
38     41       George H. W. Bush           188
39     42            Bill Clinton           188
40     43          George W. Bush           182
41     44            Barack Obama           185

In [13]:
ds

    order                    name  new readings quality
0       1       George Washington           189    Good
1       2              John Adams           170    Good
2       3        Thomas Jefferson           189    Good
3       4           James Madison           163    Good
4       5            James Monroe           183    Good
5       6       John Quincy Adams           171    Good
6       7          Andrew Jackson           185    Good
7       8        Martin Van Buren           168    Good
8       9  William Henry Harrison           173    Good
9      10              John Tyler           183    Good
10     11           James K. Polk           173    Good
11     12          Zachary Taylor           173    Good
12     13        Millard Fillmore           175    Good
13     14         Franklin Pierce           178    Good
14     15          James Buchanan           183    Good
15     16         Abraham Lincoln           193    Good
16     17          Andrew Johnson           178    Good
17     18        Ulysses S. Grant           173    Good
18     19     Rutherford B. Hayes           174    Good
19     20       James A. Garfield           183    Good
20     21       Chester A. Arthur           183    Good
21     23       Benjamin Harrison           168    Good
22     25        William McKinley           170    Good
23     26      Theodore Roosevelt           178    Good
24     27     William Howard Taft           182    Good
25     28          Woodrow Wilson           180    Good
26     29       Warren G. Harding           183    Good
27     30         Calvin Coolidge           178    Good
28     31          Herbert Hoover           182    Good
29     32   Franklin D. Roosevelt           188    Good
30     33         Harry S. Truman           175    Good
31     34    Dwight D. Eisenhower           179    Good
32     35         John F. Kennedy           183    Good
33     36       Lyndon B. Johnson           193    Good
34     37           Richard Nixon           182    Good
35     38             Gerald Ford           183    Good
36     39            Jimmy Carter           177    Good
37     40           Ronald Reagan           185    Good
38     41       George H. W. Bush           188    Good
39     42            Bill Clinton           188    Good
40     43          George W. Bush           182    Good
41     44            Barack Obama           185    Good

In [ ]:
ds.drop(columns=['quality'],inplace=True)

In [16]:
ds

    order                    name  new readings
0       1       George Washington           189
1       2              John Adams           170
2       3        Thomas Jefferson           189
3       4           James Madison           163
4       5            James Monroe           183
5       6       John Quincy Adams           171
6       7          Andrew Jackson           185
7       8        Martin Van Buren           168
8       9  William Henry Harrison           173
9      10              John Tyler           183
10     11           James K. Polk           173
11     12          Zachary Taylor           173
12     13        Millard Fillmore           175
13     14         Franklin Pierce           178
14     15          James Buchanan           183
15     16         Abraham Lincoln           193
16     17          Andrew Johnson           178
17     18        Ulysses S. Grant           173
18     19     Rutherford B. Hayes           174
19     20       James A. Garfield           183
20     21       Chester A. Arthur           183
21     23       Benjamin Harrison           168
22     25        William McKinley           170
23     26      Theodore Roosevelt           178
24     27     William Howard Taft           182
25     28          Woodrow Wilson           180
26     29       Warren G. Harding           183
27     30         Calvin Coolidge           178
28     31          Herbert Hoover           182
29     32   Franklin D. Roosevelt           188
30     33         Harry S. Truman           175
31     34    Dwight D. Eisenhower           179
32     35         John F. Kennedy           183
33     36       Lyndon B. Johnson           193
34     37           Richard Nixon           182
35     38             Gerald Ford           183
36     39            Jimmy Carter           177
37     40           Ronald Reagan           185
38     41       George H. W. Bush           188
39     42            Bill Clinton           188
40     43          George W. Bush           182
41     44            Barack Obama           185

In [20]:
ds['new readings'] < 175

0     False
1      True
2     False
3      True
4     False
5      True
6     False
7      True
8      True
9     False
10     True
11     True
12    False
13    False
14    False
15    False
16    False
17     True
18     True
19    False
20    False
21     True
22     True
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
Name: new readings, dtype: bool

In [21]:
ds[ds['new readings']>=175]

    order                   name  new readings
0       1      George Washington           189
2       3       Thomas Jefferson           189
4       5           James Monroe           183
6       7         Andrew Jackson           185
9      10             John Tyler           183
12     13       Millard Fillmore           175
13     14        Franklin Pierce           178
14     15         James Buchanan           183
15     16        Abraham Lincoln           193
16     17         Andrew Johnson           178
19     20      James A. Garfield           183
20     21      Chester A. Arthur           183
23     26     Theodore Roosevelt           178
24     27    William Howard Taft           182
25     28         Woodrow Wilson           180
26     29      Warren G. Harding           183
27     30        Calvin Coolidge           178
28     31         Herbert Hoover           182
29     32  Franklin D. Roosevelt           188
30     33        Harry S. Truman           175
31     34   Dwight D. Eisenhower           179
32     35        John F. Kennedy           183
33     36      Lyndon B. Johnson           193
34     37          Richard Nixon           182
35     38            Gerald Ford           183
36     39           Jimmy Carter           177
37     40          Ronald Reagan           185
38     41      George H. W. Bush           188
39     42           Bill Clinton           188
40     43         George W. Bush           182
41     44           Barack Obama           185

In [23]:
ds[((ds['new readings']>=175) & (ds['new readings']<=180))]

    order                  name  new readings
12     13      Millard Fillmore           175
13     14       Franklin Pierce           178
16     17        Andrew Johnson           178
23     26    Theodore Roosevelt           178
25     28        Woodrow Wilson           180
27     30       Calvin Coolidge           178
30     33       Harry S. Truman           175
31     34  Dwight D. Eisenhower           179
36     39          Jimmy Carter           177

In [26]:
ds.isnull()

    order   name  new readings
0   False  False         False
1   False  False         False
2   False  False         False
3   False  False         False
4   False  False         False
5   False  False         False
6   False  False         False
7   False  False         False
8   False  False         False
9   False  False         False
10  False  False         False
11  False  False         False
12  False  False         False
13  False  False         False
14  False  False         False
15  False  False         False
16  False  False         False
17  False  False         False
18  False  False         False
19  False  False         False
20  False  False         False
21  False  False         False
22  False  False         False
23  False  False         False
24  False  False         False
25  False  False         False
26  False  False         False
27  False  False         False
28  False  False         False
29  False  False         False
30  False  False         False
31  False  False         False
32  False  False         False
33  False  False         False
34  False  False         False
35  False  False         False
36  False  False         False
37  False  False         False
38  False  False         False
39  False  False         False
40  False  False         False
41  False  False         False

In [27]:
ds

    order                    name  new readings
0       1       George Washington           189
1       2              John Adams           170
2       3        Thomas Jefferson           189
3       4           James Madison           163
4       5            James Monroe           183
5       6       John Quincy Adams           171
6       7          Andrew Jackson           185
7       8        Martin Van Buren           168
8       9  William Henry Harrison           173
9      10              John Tyler           183
10     11           James K. Polk           173
11     12          Zachary Taylor           173
12     13        Millard Fillmore           175
13     14         Franklin Pierce           178
14     15          James Buchanan           183
15     16         Abraham Lincoln           193
16     17          Andrew Johnson           178
17     18        Ulysses S. Grant           173
18     19     Rutherford B. Hayes           174
19     20       James A. Garfield           183
20     21       Chester A. Arthur           183
21     23       Benjamin Harrison           168
22     25        William McKinley           170
23     26      Theodore Roosevelt           178
24     27     William Howard Taft           182
25     28          Woodrow Wilson           180
26     29       Warren G. Harding           183
27     30         Calvin Coolidge           178
28     31          Herbert Hoover           182
29     32   Franklin D. Roosevelt           188
30     33         Harry S. Truman           175
31     34    Dwight D. Eisenhower           179
32     35         John F. Kennedy           183
33     36       Lyndon B. Johnson           193
34     37           Richard Nixon           182
35     38             Gerald Ford           183
36     39            Jimmy Carter           177
37     40           Ronald Reagan           185
38     41       George H. W. Bush           188
39     42            Bill Clinton           188
40     43          George W. Bush           182
41     44            Barack Obama           185